<a href="https://colab.research.google.com/github/aezamsos/data-statistics-analytics-python/blob/main/ArraysRevision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
zeros_arr = np.zeros((2, 3))
ones_arr = np.ones((2, 3))
empty_arr = np.empty((2, 3))
random_arr = np.random.rand(2, 3)
print(arr1)
print(zeros_arr)
print(ones_arr)
print(empty_arr)

random_arr = np.random.rand(2, 3)
print(random_arr )
identity_matrix = np.eye(3)

[1 2 3 4 5]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[2.99363342e-316 0.00000000e+000 6.75579800e-310]
 [1.92208698e+227 2.47938862e-091 5.51006653e-310]]
[[0.81832009 0.54256735 0.94141532]
 [0.58424668 0.29894711 0.83240965]]


In [ ]:

print(identity_matrix)
# Array manipulation methods
arr2 = np.array([6, 7, 8, 9, 10])

# Concatenate arrays
concatenated_arr = np.concatenate((arr1, arr2))
print("Concatenated array:", concatenated_arr)

# Reshape array
reshaped_arr = arr1.reshape(1, 5)
print("Reshaped array:", reshaped_arr)

# Stack arrays vertically
stacked_arr_v = np.vstack((arr1, arr2))
print("Vertically stacked array:", stacked_arr_v)

# Stack arrays horizontally
stacked_arr_h = np.hstack((arr1, arr2))
print("Horizontally stacked array:", stacked_arr_h)

# Split array
split_arr = np.split(arr1, 5)
print("Split array:", split_arr)

# Append to array
appended_arr = np.append(arr1, 6)
print("Appended array:", appended_arr)

# Insert into array
inserted_arr = np.insert(arr1, 2, 10)
print("Inserted array:", inserted_arr)

# Delete from array
deleted_arr = np.delete(arr1, 2)
print("Deleted array:", deleted_arr)

# Unique elements
unique_elements = np.unique(np.concatenate((arr1, arr1)))
print("Unique elements:", unique_elements)




[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Concatenated array: [ 1  2  3  4  5  6  7  8  9 10]
Reshaped array: [[1 2 3 4 5]]
Vertically stacked array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Horizontally stacked array: [ 1  2  3  4  5  6  7  8  9 10]
Split array: [array([1]), array([2]), array([3]), array([4]), array([5])]
Appended array: [1 2 3 4 5 6]
Inserted array: [ 1  2 10  3  4  5]
Deleted array: [1 2 4 5]
Unique elements: [1 2 3 4 5]


In [ ]:
import numpy as np

# Assuming arr1, arr2 from the previous code are defined

# Element-wise addition
added_arr = arr1 + arr2
print("Element-wise addition:", added_arr)

# Element-wise subtraction
subtracted_arr = arr1 - arr2
print("Element-wise subtraction:", subtracted_arr)

# Element-wise multiplication
multiplied_arr = arr1 * arr2
print("Element-wise multiplication:", multiplied_arr)

# Element-wise division
divided_arr = arr1 / arr2
print("Element-wise division:", divided_arr)

# Dot product
dot_product = np.dot(arr1, arr2)
print("Dot product:", dot_product)

# Other mathematical operations
print("Sum of elements in arr1:", np.sum(arr1))
print("Mean of elements in arr1:", np.mean(arr1))
print("Standard deviation of elements in arr1:", np.std(arr1))
print("Maximum element in arr1:", np.max(arr1))
print("Minimum element in arr1:", np.min(arr1))

sqrt_arr = np.sqrt(arr1)
print("The square root of array 1", arr1)

#Example with 2D array
arr3 = np.array([[1,2],[3,4]])
arr4 = np.array([[5,6],[7,8]])
print("Sum of all elements in arr3:", np.sum(arr3))
print("Sum of elements in each column of arr3:", np.sum(arr3,axis=0))
print("Sum of elements in each row of arr3:", np.sum(arr3,axis=1))

print("Matrix multiplication of arr3 and arr4", np.dot(arr3,arr4))


Element-wise addition: [ 7  9 11 13 15]
Element-wise subtraction: [-5 -5 -5 -5 -5]
Element-wise multiplication: [ 6 14 24 36 50]
Element-wise division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Dot product: 130
Sum of elements in arr1: 15
Mean of elements in arr1: 3.0
Standard deviation of elements in arr1: 1.4142135623730951
Maximum element in arr1: 5
Minimum element in arr1: 1
The square root of array 1 [1 2 3 4 5]
Sum of all elements in arr3: 10
Sum of elements in each column of arr3: [4 6]
Sum of elements in each row of arr3: [3 7]
Matrix multiplication of arr3 and arr4 [[19 22]
 [43 50]]


In [ ]:
import numpy as np

# Assuming arr1 from the previous code is defined
# If not, uncomment the following line:
# arr1 = np.array([1, 2, 3, 4, 5])

# Mean
mean_val = np.mean(arr1)
print("Mean:", mean_val)

# Median
median_val = np.median(arr1)
print("Median:", median_val)

# Variance
variance_val = np.var(arr1)
print("Variance:", variance_val)

# Standard Deviation
std_dev_val = np.std(arr1)
print("Standard Deviation:", std_dev_val)

# Minimum
min_val = np.min(arr1)
print("Minimum:", min_val)

# Maximum
max_val = np.max(arr1)
print("Maximum:", max_val)


Mean: 3.0
Median: 3.0
Variance: 2.0
Standard Deviation: 1.4142135623730951
Minimum: 1
Maximum: 5


In [ ]:

import numpy as np

# Example matrices
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Dot product
dot_product_result = np.dot(matrix_a, matrix_b)
print("Dot Product:\n", dot_product_result)

# Inverse (only for square matrices)
try:
  inverse_a = np.linalg.inv(matrix_a)
  print("Inverse of matrix_a:\n", inverse_a)
except np.linalg.LinAlgError:
  print("Matrix_a is singular and does not have an inverse.")

# Determinant (only for square matrices)
determinant_a = np.linalg.det(matrix_a)
print("Determinant of matrix_a:", determinant_a)


Dot Product:
 [[19 22]
 [43 50]]
Inverse of matrix_a:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of matrix_a: -2.0000000000000004


In [ ]:
# Boolean & Comparison operations

comparison_arr = np.greater(arr1, 3)
where_condition = np.where(arr1>3)

print(comparison_arr)
print(where_condition)

[False False False  True  True]
(array([3, 4]),)


In [ ]:
import numpy as np

# Assuming arr1 from the previous code is defined
# If not, uncomment the following line:
# arr1 = np.array([1, 2, 3, 4, 5])

# Sorting
sorted_arr = np.sort(arr1)
print("Sorted array:", sorted_arr)

# Finding minimum and maximum
min_val = np.min(arr1)
max_val = np.max(arr1)
print("Minimum value:", min_val)
print("Maximum value:", max_val)

# Finding unique elements
unique_elements = np.unique(arr1)
print("Unique elements:", unique_elements)

# Searching (example: finding the index of a specific element)
element_to_find = 3
index = np.where(arr1 == element_to_find)
print(f"Index of {element_to_find}:", index)


Sorted array: [1 2 3 4 5]
Minimum value: 1
Maximum value: 5
Unique elements: [1 2 3 4 5]
Index of 3: (array([2]),)


In [ ]:
np.random.seed(42)
random_ints = np.random.randint(1, 10, (3,3))
random_choice = np.random.choice(arr1, 3)
print(random_ints)
print(random_choice)

[[7 4 8]
 [5 7 3]
 [7 8 5]]
[4 3 5]
